version: '1.0'

services:
  db:
    image: mysql:latest
    container_name: mysql-server
    volumes:
      - mysql-data:/data
    networks:
      - app-network

    # Set the environment variables for the database
    environment:
      - MYSQL_ROOT_PASSWORD=passroot
      - MYSQL_DATABASE=ccfinal
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  backend:
    image: monitor:3

    environment:
      - DB_NAME=ccfinal
      - DB_USER=user
      - DB_PASSWORD=pass

    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8080:8080"

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge