apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
type: Opaque
stringData:
  username: {{ ".Values.username" | b64enc }}
  password: {{ .Values.password | b64enc }}
  dbname: {{ .Values.dbname | b64enc }}
  rootpassword: {{ .Values.rootpassword | b64enc }}

