monitor:
  name: monitor
  port: 8080
  intervalM: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  volumeMounts:
    - name: config
      mountPath: /app/config.yaml
      subPath: config.yaml
  volumes:
    - name: config
      configMap:
        name: monitor-configmap

username: user
password: pass
dbname: ccfinal
rootpassword: passroot
MYSQL:
  name: mysql
  replicaCount: 2
  waddr: "mysql-0.mysql-w:3306"
  raddr: "mysql-0.mysql-r:3306"
  image:
    repository: mysql
    #pullPolicy: IfNotPresent
    tag: "5.7"
  ports:
    - name: tcp
      protocol: TCP
      containerPort: 3306
  terminationGracePeriodSeconds: 10
  environment:
    MYSQL_USER: username
    MYSQL_PASSWORD: password
    MYSQL_DATABASE: dbname
    MYSQL_ROOT_PASSWORD: rootpassword
  service:
    type: ClusterIP
    name: tcp
    protocol: TCP
    port: 3306

  resources:
    requests:
      memory: "1Gi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "500m"

  volumeMounts:
    - name: data
      mountPath: /var/lib/tempmysql

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi