apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi  
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: "/data/redis" 
