apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  labels:
    app: weather-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: weather-app
        image: blackberryninja/weather-monitor:test
        imagePullPolicy: "Always"
        command: ["python3", "listener.py"]
        ports:
        - containerPort: 12345
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: TTL
          valueFrom:
            configMapKeyRef:
              name: weather-app-config
              key: ttl
        - name: CITY
          valueFrom:
            configMapKeyRef:
              name: weather-app-config
              key: city
        - name: API_KEY
          valueFrom:
            configMapKeyRef:
              name: weather-app-config
              key: api-key
        - name: REDIS_PASSWORD # REDIS_PASSWORD is used by the app to authenticate with the redis host
          valueFrom:
            secretKeyRef:
              name: redis-secret # name of the secret
              key: redis-password # import the value of 'redis-password' from app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: weather-app
spec:
  # type: NodePort
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345
