apiVersion: apps/v1
kind: Deployment

metadata:
  name: monitor

spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: monitor
          image: fornacis/monitor:3
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: dbname
          ports:
            - containerPort: 8080
              name: monitor
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: configmap
